[symlinks]
gitconfig = "/home/kippster/.gitconfig"
neofetch = "/home/kippster/.config/neofetch/config.conf"
p10k = "/home/kippster/.p10k.zsh"
tmux = "/home/kippster/.tmux.conf"
vimrc = "/home/kippster/.vimrc"
zshrc = "/home/kippster/.zshrc"

[templates]
