[all]
depends = ["i3", "alacritty", "shell", "git", "font"]

[terminal]
depends = ["shell", "git"]

[i3.files]
dunstrc = "~/.config/dunst/dunstrc"
picom = "~/.config/picom/picom.conf"
i3 = "~/.config/i3/config"
xinitrc = "~/.xinitrc"
# dconf = "~/dconf/user"

[alacritty.files]
alacritty = "~/.config/alacritty/alacritty.yml"

[shell]
depends = ["neofetch"]

[shell.files]
tmux = "~/.tmux.conf"
zshrc = "~/.zshrc"
vimrc = "~/.vimrc"
p10k = "~/.p10k.zsh"
neofetch = "~/.config/neofetch/config.conf"

[neofetch.variables]
packages = false
battery = true

[git.files]
gitconfig = "~/.gitconfig"

[font.files]
# Krever at MS fonts er installert
fontconfig = "~/.config/fontconfig/fonts.conf"

[gtk3.files]
gtk3 = "~/.config/gtk-3.0/settings.ini"